services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: examplepass

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: testrootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: