name: PostgreSQL Docker Build Test

on:
  push:
    branches:
      - docker
    paths:
      - '/Docker/**.SQL'
      - 'SQL/**.SQL'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Test Docker Image
        run: |
          docker build -t postgres-test -f Docker/PostgreSQL.Dockerfile .
          docker run --rm -p 9999:9999 postgres-test