name: Test Actions Workflow

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run tests
              run: echo "Running tests..."

    branche-check:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check branch name
              run: echo "Current branch is ${{ github.ref_name }}"

            - name: Run branche-check
              run: echo "Running branch check..."

            - name: Run additional tests
              run: |
                if [[ "${{ github.ref_name }}" == "main" ]]; then
                  echo "Running tests for main branch..."
                else
                  echo "Running tests for non-main branch..."
                fi

    other-branches-check:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Check branch name
              run: echo "Current branch is ${{ github.ref_name }}"

            - name: Repository has other branches Check
              run: |
                GOLANG_BRANCH=${{ github.ref_name == 'golang' }}
                echo "GOLANG_BRANCH: $GOLANG_BRANCH"
                CREDENTIAL_BRANCH=${{ github.ref_name == 'credential' }}
                echo "CREDENTIAL_BRANCH: $CREDENTIAL_BRANCH"
                DOCKER_BRANCH=${{ github.ref_name == 'docker' }}
                echo "DOCKER_BRANCH: $DOCKER_BRANCH"
                NET_BRANCH=${{ github.ref_name == 'net' }}
                echo "NET_BRANCH: $NET_BRANCH"